services:
  app:
    entrypoint:
    - sleep
    - infinity
    ports:
      - "4200:4200"
    expose:
      - "4200"
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: development
    volumes:
      - type: bind
        source: ./
        target: /medieval-dynasty-calculator